name: barcode_scan
description: A flutter plugin for scanning 2D barcodes and QRCodes via camera.
version: 2.0.1
homepage: https://github.com/mintware-de/flutter_barcode_reader

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.19.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: de.mintware.barcode_scan
        pluginClass: BarcodeScanPlugin
      ios:
        pluginClass: BarcodeScanPlugin